
env_args:
    env: 'FlightSimulator'
    source: 'handyrl.envs.nishika.env'
    #env: 'Geister'
    #env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: False 
    observation: False
    gamma: 0.8
    forward_steps: 32 
    compress_steps: 4
    entropy_regularization: 2.0e-4 
    entropy_regularization_decay: 0.3
    update_episodes: 200
    batch_size: 200 
    minimum_episodes: 100
    maximum_episodes: 30000
    epochs: -1
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 8
    lambda: 0.7
    policy_target: 'UPGO' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent: ['random']
    seed: 0
    restart_epoch: 0


worker_args:
    server_address: ''
    num_parallel: 8 

